version: "3.9"

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.local      