version: "3.9"

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    command: npm start
    # Sem volumes de código em produção 